compiler/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^compile/$', views.compile, name='compile'),
    url(r'^invoke/$', views.invoke, name='invoke'),
    url(r'^result/$', views.result, name='result'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^compiler/', include('compiler.urls', namespace="compiler")),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex:/polls/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex:/polls/5
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

compiler/models.py
from django.db import models

# Create your models here.

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

compiler/views.py
import logging, json

from django.shortcuts import render
from django.http import HttpResponse

from quackCompiler.invokeCompile import invoke, getParamList, saveToFile, readResult

# Create your views here.

#Get an instance of a logger
logger = logging.getLogger(__name__)

def index(request):
    return render(request, 'compiler/index.html')

def compile(request):
    response=HttpResponse()
    response['Content-Type']="text/javascript"
    # Get the Post
    modelScript =  request.POST['script']
    modelName =  request.POST['modelName']
    paramCount =  request.POST['paramCount']
    modelName = modelName.replace(' ','')
    modelName = modelName.lower()
    paramCount = int(paramCount)            # Convert the count from string to int
    content = modelScript
    paramList = ''
    if paramCount > 0:
        jsonContent = request.POST['jsonContent']
        paramList = getParamList(jsonContent)
        for (k,v) in paramList.items():
            content = str(modelScript).replace("<%"+k+"%>", v)
        logger.error(paramList)

    logger.error(content)
    logger.error("Param count is:"+str(paramCount))

    outputpath = '/Users/xuzhang/Documents/TOOLS/PYTHON/Django/django_example/data/model/'    # Model's path and the compiler's input

    saveToFile(modelName, modelScript, paramCount, paramList, outputpath)

    outpath = '/Users/xuzhang/Documents/TOOLS/PYTHON/Django/django_example/data/result/'     # The result's saving path.
    # invoke the compiler
    inpath = outputpath+modelName+'.json'   # Compiler's infile.
    invoke(inpath, outpath)     # Invoke the compiler.
    count, resultlist = readResult(outpath)         # Read the result from file.

    result.count = count
    result.resultlist = resultlist

    return HttpResponse(json.dumps({"resultcount":count,"resultlist":resultlist}))

def result(request):
    return render(request, 'compiler/result.html')

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice
# Create your views here.

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set 
        to be published in the future).
        """
        return Question.objects.filter(
            pub_date__lte = timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
#    try:
#        question = Question.objects.get(pk = question_id)
#    except Question.DoesNotExist:
#        raise Http404("Question does not exist.")
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html',{
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
    return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

compiler/templates/compiler/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="code visualization">
    <meta name="keywords" content="code visualization, visualize code, code, c, c++, pyhton, java">
    <meta name="UI-Designed-By" content="Fang Wei">
    <title>Compiler</title>
    <link href="/static/compiler/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/compiler/css/style.css" rel="stylesheet">
      <link href="/static/compiler/css/JSAV.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="/static/compiler/js/bootstrap.min.js"></script>
    <script src="/static/compiler/js/jquery-linedtextarea.js"></script>
     <script src="/static/compiler/js/coding.js"></script>
     <script src="/static/compiler/js/jquery.transit.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.1.3/ace.js"></script>
      <script src="/static/compiler/js/raphael.js"></script>
      <script src="/static/compiler/js/JSAV.js"></script>

      <script type="text/javascript">
      $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
        });

        paramCount = 1; // Count the parameter list.

        $(function(){
            $('[data-action="run"]').click(function(event) {
            var editor = ace.edit("coding");
            var content = editor.getSession().getValue();

            var param = {};
            param.script = content;
            param.paramCount = paramCount -1;
            param.modelName = $("#model-name").val();

            if(paramCount-1 > 0){
                jsonContent = '{';
                for (var i=1;i<paramCount;i++){
                    //param.param[i] = $("#Param"+i).val();
                    if(i == 1){
                        jsonContent = jsonContent + '\"Param' + i + '\":\"'+ $("#Param"+i).val() +'\"'
                    } else {
                        jsonContent = jsonContent + ',\"Param' + i + '\":\"'+ $("#Param"+i).val() +'\"'
                    }

                }
                jsonContent = jsonContent+"}"
                param.jsonContent = jsonContent;
            }

            $.ajax({
                type:"POST",
                data:param,
                url: "{% url 'compiler:compile' %}",
                success : function(data) {
                    data = JSON.parse(data);
                    alert("Success!!")
                    //alert(data["resultlist"].length)
                    $("#resultlist").text("");     //Clear the div.
                    for (var i=0; i < data["resultlist"].length; i++) {
                        $("#resultlist").append(data["resultlist"][i])
                        $("#resultlist").append("<br />")
                    }

                    //$("#resultlist").append(data["resultlist"]);    //Append the result to div.
                }
            });
          });

          $('#add-param').click(function(event) {
                label = "Param"+paramCount;
                //$('#param-list').append('<div id="param-'+label+'">'+label+':<input type="text" id="'+label+'" style="width:360px;"/><br /><br /></div>')
                $('#param-list').append('<tr id="param-'+label+'"><td style="width:100px;">'+label+':</td><td style="width:360px;"><input type="text" id="'+label+'" style="width:300px;" /></td></tr></div>')
                paramCount = paramCount + 1;
          });

          $('#remove-param').click(function(event) {
                if(paramCount > 1){
                    paramCount = paramCount - 1;

                    label = "Param"+paramCount;
                    $("#param-"+label).remove();

                } else {
                    paramCount = 1;
                }
          });

        });
      </script>
  </head>

<body id="coding_body">
    <div id="header">
      <div class="container monikai">
          <a href="{% url 'compiler:index' %}" id="logo" class="pull-left"><span class="glyphicon glyphicon-chevron-left"></span><span class="glyphicon glyphicon-wrench"></span><span class="glyphicon glyphicon-chevron-right"></span>QuackCompiler</a>
         <ul>
                  <li class="active"><a href="{% url 'compiler:index' %}">» Coding</a></li>
          </ul>
      </div>
    </div>
    <form action="{% url 'compiler:compile' %}" id="coding-coding">
    <div class="container monokai">
      <div class="row">
        <div class="col-xs-6">
                    <h4>The Model's Name : <span class="glyphicon glyphicon-exclamation-sign" data-placement="bottom" data-toggle="popover" title="Read Me" data-content="You must Give your model a name befor you Run or Save!"></span></h4>
                    <input type="text" id="model-name" />
                   <h4>Your code here : <span class="glyphicon glyphicon-exclamation-sign" data-placement="bottom" data-toggle="popover" title="Read Me" data-content="Try coding and debugging by yourself!      You have two options:     1. TYPE your code here, 2. or click on [Attach] button to UPLOAD a local file. Note: the existing code will be replaced by the content uploaded! "></span></h4>
              <div id="coding"></div>
          </div>
        <div class="col-xs-6">
          <h4>Parameters :</h4>
          <div id="v">
              <div id="param-list">
              <br />
                  <table border="0">
                      <tr>
                        <th style="width:100px;">Name</th>
                        <th style="width:360px;">Value</th>
                      </tr>
                  </table>

            </div>
              <br />
              <center><button type="button" id="add-param">Add</button><button type="button" id="remove-param">Remove</button></center>
          </div>
          <div id="errorMsg">
            » console: <br>
              <div id="resultlist"></div>
          </div>
        </div>
        <div class="coding-btn-group btn-group pull-left btn-group-md">
            <div class="btn-group dropup">
            <button type="button" class="btn btn-default dropdown-toggle  " data-toggle="dropdown">
              <span class="glyphicon glyphicon-wrench"></span> Theme
              <span class="caret"></span>
              <span class="sr-only">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu" id="changeTheme" role="menu">
              <li><a href="#" data-theme="monokai">Monokai <span class="glyphicon glyphicon-ok"></span></a></li>
              <li><a href="#" data-theme="cobalt">Cobalt</a></li>
              <li><a href="#" data-theme="solarized_light">Solarized</a></li>
              <input type="hidden" name="theme" value="monokai">
            </ul>
          </div>
            <button type="button" class="btn btn-default" data-action="run">
              <span class="glyphicon glyphicon-play"></span>
              Run
            </button>
            <button type="button" class="btn btn-default btn-file">
              <input type="file" accept=".txt">
              <span class="glyphicon glyphicon-paperclip"></span> Attach
            </button>

          </div>
      </div>
        </div>
     </form>
  </body>
</html>

compiler/templates/compiler/result.html
{% if result_message %}<p><strong>{{ result_message }}</strong></p>{% endif %}
<h1>The result is:</h1>
{% if result %}<p><strong>{{ result }}</strong></p>{% endif %}

<a href="/compiler">返回</a>

compiler/templates/compiler/test.html
<form action="{% url 'compiler:invoke' %}" method="post">
	{% csrf_token %}
	file1:<input type="text" name="file1"/> <br />
	<textarea name="script" cols="100" rows="10" > </textarea>
	<br />
	<input type="submit" value="submit" />
</form>




<script type="text/javascript">
      $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
        });

        paramCount = 1; // Count the parameter list.

        $(function(){
            $('[data-action="run"]').click(function(event) {
            var editor = ace.edit("coding");
            var content = editor.getSession().getValue();

            var jsonContent = '{"script":"'+content+'"';

            var jsonContent = jsonContent + ',' + '"paramCount":"' + (paramCount-1) + '"';

            var param = {};


            var paramList = [];
            if(paramCount-1 > 0){
                jsonContent = jsonContent + ',"paramList":[';
                for (var i=1;i<paramCount;i++){
                    //param.param[i] = $("#Param"+i).val();
                    if(i == 1){
                        jsonContent = jsonContent + '{\"Param' + i + '\":\"'+ $("#Param"+i).val() +'\"}'
                    } else {
                        jsonContent = jsonContent + ',{\"Param' + i + '\":\"'+ $("#Param"+i).val() +'\"}'
                    }

                }
                jsonContent = jsonContent+"]"
            }
            jsonContent = jsonContent+"}"
            alert(jsonContent);
            param.jsonContent = jsonContent;
            $.ajax({
                type:"POST",
                data:param,
                url: "{% url 'compiler:compile' %}",
                //url: "/compiler/compile",
                success : function(data) {
                    alert("Success!!")
                }
            });
          });

          $('#add-param').click(function(event) {
                label = "Param"+paramCount;
                $('#param-list').append('<div id="param-'+label+'">'+label+': <input type="text" id="'+label+'"/> <br /><br /></div>')
                paramCount = paramCount + 1;
          });

          $('#remove-param').click(function(event) {
                if(paramCount > 1){
                    paramCount = paramCount - 1;

                    label = "Param"+paramCount;
                    $("#param-"+label).remove();

                } else {
                    paramCount = 1;
                }
          });

        });
      </script>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
		<input type="radio" name="choice" id="choice{{ forloop.counter}}" value="{{ choice.id }}" />
		<label for="choice{{ forloop.counter}}">{{ choice.choice_text }}</label><br />
	{% endfor %}
	<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
	<ul>
	{% for question in latest_question_list %}
	<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>

	{% for choice in question.choice_set.all %}
		<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
	{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>